#!/usr/bin/env python3
from pathlib import Path
import shutil

import nmtestrunner
"""
                            Config
"""

nmtestrunner.config(
    # Directory that all testing stuff is dumped into
    testingroot="/autograder/testing",
    # Location of student's source code
    studentroot="/autograder/submission",
    # Location of the testset
    testsetdir="/autograder/source/cs-15-autograding-repo/testset",
    # Location of all the testing framework code
    testframeworkroot="/autograder/source/cs-15-autograding-repo/framework",
    # Path to testing Makefile
    makefile="",
    # All the programs the student's Makefile is responsible for
    studentexecutables=["CalcYouLater"]
)
"""
                        Run the autograder
"""
nmtestrunner.setup({})
shutil.copy("link/Datum.cpp", "/autograder/testing/student.1")
shutil.copy("link/Datum.h", "/autograder/testing/student.1")
nmtestrunner.main(**vars(nmtestrunner.parseArgs()))
