#!/usr/bin/env python3
from pathlib import Path
import shutil
import subprocess
import os

wd = os.getcwd()
os.chdir('cs-15-autograding-repo')
subprocess.run(["git", "pull"], cwd = "/autograder/")
os.chdir(wd)

import nmtestrunner
"""
                            Config
"""

nmtestrunner.config(
    # Directory that all testing stuff is dumped into
    testingroot="testing",
    # Location of student's source code
    studentroot="submission",
    # Location of the testset
    testsetdir="source/cs-15-autograding-repo/testset",
    # Location of all the testing framework code
    testframeworkroot="source/cs-15-autograding-repo/framework",
    # Path to testing Makefile
    makefile="",
    # All the programs the student's Makefile is responsible for
    studentexecutables=["CalcYouLater"]
)
"""
                        Run the autograder
"""
nmtestrunner.setup({})
shutil.copy("source/link/Datum.cpp", "testing/student.1")
shutil.copy("source/link/Datum.h", "testing/student.1")
nmtestrunner.main(**vars(nmtestrunner.parseArgs()))
