[paths]
ASSIGN_ROOT ="assignments"
ASSIGN_AUTOGRADING_SUBFOLDER = ""
AUTOGRADING_ROOT = ""
REPO_REMOTE_VARNAME = "AUTOGRADING_REPO_REMOTE_PATH"

[tokens]
GRACE_TIME = 15   # 15 minutes
TOKEN_TIME = 1440 # 24 hours
STARTING_TOKENS = 5
MAX_PER_ASSIGN = 2
MANAGE_TOKENS = "true"
POSTGRES_REMOTE_VARNAME = "POSTGRES_REMOTE_PATH"

# only used with manual docker builds
[docker]
CONTAINER_REGISTRY = "ghcr.io"
CONTAINER_NAME = "gradescope-docker"
CONTAINER_TAG = "autograder-autobuild"
REGISTRY_USER_VARNAME = "GHUNAME"
REGISTRY_PASS_VARNAME = "GHPAT"

[other]
SUBMISSIONS_PER_ASSIGN = 5