#!/bin/bash
# make-symlinks
# mrussell
# 9/18/2021
# 7-16-2023 - simplified the script; load course config info from config.toml
#
# Assumes staff-bin, which contains this file, is in the root of the repo
# Assumes pdfs are named the same as the assignment name + .pdf
#
python3 -m pip install toml-cli &> /dev/null

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR/..

COURSE_NUM=$(toml get halligan.COURSE_NUM)
TERM=$(toml get halligan.TERM)
ASSIGN_ROOT=$(toml get repo.ASSIGN_ROOT)
COURSE_ROOT=/g/${COURSE_NUM}/${TERM}

# find the names of each of the assigments/labs/projects
FILES_NAMES=$(find ${ASSIGN_ROOT}/*/files -maxdepth 0 -type d | xargs -0 | rev | cut -d "/" -f 2 | rev)
for name in $FILES_NAMES; do

    # remove a symlink if it exists already
    if [ -L files/${name} ]; then
        rm files/${name}
    fi

    ln -s ${COURSE_ROOT}/${ASSIGN_ROOT}/${name}/files  files/${name}
done

SPEC_NAMES=$(find ${ASSIGN_ROOT}/*/spec -maxdepth 0 -type d | xargs -0 | rev | cut -d "/" -f 2 | rev)
for name in $SPEC_NAMES; do

    # remove a symlink if it exists already
    if [ -L public_html/${name}.pdf ]; then
        rm public_html/${name}.pdf
    fi

    ln -s ${COURSE_ROOT}/${ASSIGN_ROOT}/${name}/spec/${name}.pdf public_html/${name}.pdf
done