[common]
our_makefile = true
executable = "mem_test"
visibility = "visible"
kill_limit = 100
max_time = 60

[visible_tests]
tests = [ 
    { testname = "test01", description = "alloc 1 int" },
    { testname = "test02", description = "alloc 10 ints" },
    { testname = "test03", description = "alloc 100 ints" }, 
    { testname = "test04", description = "alloc 1000 ints" },
    { testname = "test05", description = "alloc 10000 ints" },
    { testname = "test06", description = "alloc 100000 ints" },
    { testname = "test07", description = "alloc 1000000 ints" },
    { testname = "test08", description = "alloc 10000000 ints" },
    { testname = "test09", description = "alloc 10000000 ints" },
    { testname = "test10", description = "alloc 10000000 ints", max_ram=10 },
    { testname = "test11", description = "alloc 1000 ints", max_ram = 1  },
    { testname = "test12", description = "stdout test: alloc 100000000 ints", argv=["1"] } 
    { testname = "test13", description = "test: alloc 1000000000 ints fails kill limit" } 
]