#!/bin/bash
# the autograder for gradescope
# pulls the repo copies the autograding files to /autograder/, and runs the tests. 
# note: pass along any args in case ta's run this from gs containers.
# *** If you change this file, you must also rebuild/deploy the autograder container image ***

cd /build/course-repo
git pull -f > /autograder/run_autograder_log 2>&1

cp -r assignments/$ASSIGNMENT_TITLE/* /autograder/
cp    framework/autograde.py /autograder/

cd /autograder/
chmod +x testrunner.sh
./testrunner.sh $@ > results/stdout 2>&1

if [[ $- == *i* ]]
then
    cat results/stdout
fi

python3 update_results.py